name: "Pre-release tasks"

on:
  pull_request:
    types: [ labeled ]

jobs:
  pre-release-checks:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'release')

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Mark latest version as released
        run: npx changelog-tool release
      - name: Commit changes back to branch (if any)
        run: git push
